# Generated by Django 3.0.4 on 2020-03-17 06:14

from django.db import migrations, models
import fieldValidation.models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldValidation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.CharField(max_length=200, validators=[fieldValidation.models.validate_even])),
            ],
        ),
        migrations.DeleteModel(
            name='AccountTable',
        ),
    ]
